# Generated by Django 6.1 on 2026-09-02 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insumo_ultima_alerta_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['nombre'], name='idx_insumo_nombre'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['alerta_pendiente'], name='idx_insumo_alerta_pendiente'),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['fecha'], name='idx_merma_fecha'),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['fecha', 'causa'], name='idx_merma_fecha_causa'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='idx_venta_fecha'),
        ),
    ]
