"""
Django settings for coffeestock project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import io
from pathlib import Path

import environ
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()


def _leer_env(ruta):
    """Lee el .env tolerando lo que suele pasar al editarlo a mano: espacios
    al inicio de la línea o alrededor del "=" (django-environ ignora esas
    líneas sin avisar) y la marca BOM que agregan algunos editores."""
    try:
        texto = ruta.read_text(encoding='utf-8-sig')
    except OSError:
        return
    lineas = []
    for linea in texto.splitlines():
        linea = linea.strip()
        if '=' in linea and not linea.startswith('#'):
            clave, valor = linea.split('=', 1)
            linea = f'{clave.strip()}={valor.strip()}'
        lineas.append(linea)
    environ.Env.read_env(io.StringIO('\n'.join(lineas)))


_leer_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-v1da+s@0z3^!wknf8xyn-kxl-&$m9tgjy0mo)bobok@y2hje=_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
    'pos',
    'dashboard',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:root'
LOGOUT_REDIRECT_URL = 'core:login'

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coffeestock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_groups',
            ],
        },
    },
]

WSGI_APPLICATION = 'coffeestock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_USER = env('DB_USER', default='')
DB_PASSWORD = env('DB_PASSWORD', default='')
DB_PORT = env('DB_PORT', default='')

DB_HOST = env('DB_HOST', default='localhost')
if DB_PORT:
    DB_HOST = f'{DB_HOST},{DB_PORT}'


def _detectar_driver_odbc():
    """Usa DB_DRIVER si está definido; si no, el driver ODBC de SQL Server
    más reciente que haya instalado en la máquina (18, 17, ...)."""
    driver = env('DB_DRIVER', default='')
    if driver:
        return driver
    try:
        import pyodbc
        instalados = [d for d in pyodbc.drivers() if d.startswith('ODBC Driver') and 'SQL Server' in d]
    except Exception:
        instalados = []
    if instalados:
        return max(instalados, key=lambda d: int(''.join(c for c in d if c.isdigit()) or 0))
    return 'ODBC Driver 18 for SQL Server'


DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': env('DB_NAME', default='CoffeeStockDB'),
        'HOST': DB_HOST,
        'OPTIONS': {
            'driver': _detectar_driver_odbc(),
            # Para desarrollo local: acepta el certificado autofirmado que
            # SQL Server genera por defecto (el driver 18 lo exige).
            'extra_params': 'TrustServerCertificate=yes',
        },
    }
}

# Con DB_USER y DB_PASSWORD se usa SQL Authentication. Si falta alguno,
# mssql-django agrega Trusted_Connection=yes (Windows Authentication).
if DB_USER and DB_PASSWORD:
    DATABASES['default']['USER'] = DB_USER
    DATABASES['default']['PASSWORD'] = DB_PASSWORD


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'coffeestock' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Imágenes de productos subidas desde el dashboard.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Las alertas de stock bajo se envían por uno de estos proveedores:
#   consola  -> el correo se imprime en la terminal de runserver (no sale a internet)
#   sendgrid -> API de SendGrid (requiere API key y remitente verificado)
#   smtp     -> cualquier servidor SMTP (Gmail, Outlook, Mailtrap, etc.)
# Si ALERTA_EMAIL_PROVEEDOR está vacío se elige solo: sendgrid si hay API key,
# smtp si hay EMAIL_HOST_USER, y consola en cualquier otro caso.

SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = env('SENDGRID_FROM_EMAIL', default='')

SMTP_USUARIO = env('EMAIL_HOST_USER', default='')

ALERTA_EMAIL_PROVEEDOR = env('ALERTA_EMAIL_PROVEEDOR', default='').strip().lower()
if not ALERTA_EMAIL_PROVEEDOR:
    if SENDGRID_API_KEY:
        ALERTA_EMAIL_PROVEEDOR = 'sendgrid'
    elif SMTP_USUARIO:
        ALERTA_EMAIL_PROVEEDOR = 'smtp'
    else:
        ALERTA_EMAIL_PROVEEDOR = 'consola'

# Quién recibe las alertas: uno o varios correos separados por coma.
# SENDGRID_ADMIN_EMAIL se sigue aceptando por compatibilidad con .env viejos.
ALERTA_EMAIL_DESTINATARIOS = [
    correo.strip()
    for correo in env.list(
        'ALERTA_EMAIL_DESTINATARIOS', default=env.list('SENDGRID_ADMIN_EMAIL', default=[])
    )
    if correo.strip()
]

# Quién aparece como remitente. En SendGrid DEBE ser el correo verificado
# como "Sender" en tu cuenta; en SMTP normalmente es tu mismo usuario.
if ALERTA_EMAIL_PROVEEDOR == 'sendgrid':
    DEFAULT_FROM_EMAIL = SENDGRID_FROM_EMAIL
else:
    DEFAULT_FROM_EMAIL = env('EMAIL_FROM', default=SMTP_USUARIO or 'alertas@coffeestock.local')

if ALERTA_EMAIL_PROVEEDOR == 'smtp':
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': env('EMAIL_HOST', default='smtp.gmail.com'),
                'port': env.int('EMAIL_PORT', default=587),
                'username': SMTP_USUARIO,
                'password': env('EMAIL_HOST_PASSWORD', default=''),
                'use_tls': env.bool('EMAIL_USE_TLS', default=True),
                'timeout': 15,
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }


# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
